//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.h
//  @ Date : 21.03.2024
//  @ Author :
//
//


#if !defined(_BANK_H)
#define _BANK_H
#include "Oddzial.h"
#include <string>

using namespace std;


class Bank {
public:
	string getNazwa();
	void setOddzial(int numerOddzialu, string adres);
	void wypiszOddzial();
	Bank(string nazwa);
	~Bank();
private:
	string nazwa;
	Oddzial * oddzial;
};

#endif  //_BANK_H
