//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.cpp
//  @ Date : 21.03.2024
//  @ Author :
//
//


#include "Bank.h"
#include "Oddzial.h"
#include <iostream>
#include <string>

using namespace std;

string Bank::getNazwa() {
    return nazwa;
}

void Bank::setOddzial(int numerOddzialu, string adres) {
    oddzial->setAdres(adres);
    oddzial->setNumerOddzial(numerOddzialu);
}

void Bank::wypiszOddzial(){
    cout << oddzial->getNumerOddzialu() << " " << oddzial->getAdres() << endl;
}

Bank::Bank(string nazwa) {
    cout << "Konstruktor Banku" << endl;

    this->nazwa = nazwa;

    oddzial = new Oddzial;
}

Bank::~Bank() {
    delete oddzial;
    cout << "Destruktor Banku" << endl;
}

