//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Oddzial.h
//  @ Date : 21.03.2024
//  @ Author :
//
//


#if !defined(_ODDZIAL_H)
#define _ODDZIAL_H
#include <iostream>
#include <string>

using namespace std;


class Oddzial {
public:
	Oddzial();
	~Oddzial();
	int getNumerOddzialu();
	string getAdres();
	void setNumerOddzial(int numer);
	void setAdres(string adres);
private:
	int numerOddzialu;
	string adres;
};

#endif  //_ODDZIAL_H
