//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Oddzial.cpp
//  @ Date : 21.03.2024
//  @ Author :
//
//


#include "Oddzial.h"
#include <iostream>
#include <string>

using namespace std;

Oddzial::Oddzial() {
    cout << "Konstruktor Oddzialu" << endl;
}

Oddzial::~Oddzial() {
    cout << "Destruktor Oddzialu" << endl;
}

int Oddzial::getNumerOddzialu() {
    return numerOddzialu;
}

string Oddzial::getAdres() {
    return adres;
}

void Oddzial::setNumerOddzial(int numer) {
    this->numerOddzialu = numer;
}

void Oddzial::setAdres(string adres) {
    this->adres = adres;
}

