//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Firma.h
//  @ Date : 19.03.2024
//  @ Author :
//
//


#if !defined(_FIRMA_H)
#define _FIRMA_H
#include "Pracownik.h"
#include <string>
#include <iostream>
#include <vector>

using namespace std;


class Firma {
public:
	Firma(string nazwa, string nip);
	void dodajPracownika(Pracownik * pracownik);
	void usunPracownika(Pracownik * pracownik);
	void wyswietlPracownikow();
private:
	string nazwa;
	string nip;
	vector<Pracownik *> pracownicy;
};

#endif  //_FIRMA_H
