//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 19.03.2024
//  @ Author :
//
//


#include "Pracownik.h"
#include <string>
#include <iostream>
#include <vector>

using namespace std;

Pracownik::Pracownik(string imie, string nazwisko, string adresZamieszkania) {
    this->imie = imie;
    this->nazwisko = nazwisko;
    this->adresZamieszkania = adresZamieszkania;
}

string Pracownik::getImie() {
    return imie;
}

string Pracownik::getNazwisko() {
    return nazwisko;
}

string Pracownik::getAdres() {
    return adresZamieszkania;
}

