//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 19.03.2024
//  @ Author :
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H
#include <string>
#include <iostream>
#include <vector>

using namespace std;


class Pracownik {
public:
	Pracownik(string imie, string nazwisko, string adresZamieszkania);
	string getImie();
	string getNazwisko();
	string getAdres();
private:
	string imie;
	string nazwisko;
	string adresZamieszkania;
};

#endif  //_PRACOWNIK_H
