//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Autor.cpp
//  @ Date : 17.03.2024
//  @ Author :
//
//


#include "Autor.h"
#include "Ksiazka.h"
#include <string>
#include <iostream>
#include <vector>

using namespace std;

Autor::Autor(string imie, string nazwisko) {
    this->imie = imie;
    this->nazwisko = nazwisko;
}

string Autor::getImie() {
    return imie;
}

string Autor::getNazwisko() {
    return nazwisko;
}

void Autor::setKsiazki(Ksiazka *ksiazka){
    this->napisaneKsiazki.push_back(ksiazka);
}

void Autor::napisaneKsiazkiView(){
    for(int i = 0; i < napisaneKsiazki.size(); i++){
        cout << napisaneKsiazki[i]->getTytul() << endl;
    }
}

vector<Ksiazka *> Autor::getKsiazki(){
    return napisaneKsiazki;
}
