//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Autor.h
//  @ Date : 17.03.2024
//  @ Author :
//
//


#if !defined(_AUTOR_H)
#define _AUTOR_H
#include <string>

using namespace std;


class Autor {
public:
	Autor(string imie, string nazwisko);
	string getImie();
	string getNazwisko();
private:
	string imie;
	string nazwisko;
};

#endif  //_AUTOR_H
