//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Autor.h
//  @ Date : 17.03.2024
//  @ Author :
//
//


#if !defined(_AUTOR_H)
#define _AUTOR_H
#include <string>
#include <vector>

using namespace std;

class Ksiazka;
class Autor {
public:
	Autor(string imie, string nazwisko);
	string getImie();
	string getNazwisko();
	void setKsiazki(Ksiazka *ksiazka);
	void napisaneKsiazkiView();
	vector<Ksiazka *> getKsiazki();
private:
	string imie;
	string nazwisko;
	vector<Ksiazka *> napisaneKsiazki;
};

#endif  //_AUTOR_H
