//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Autor.cpp
//  @ Date : 17.03.2024
//  @ Author :
//
//


#include "Autor.h"
#include <string>

using namespace std;

Autor::Autor(string imie, string nazwisko) {
    this->imie = imie;
    this->nazwisko = nazwisko;
}

string Autor::getImie() {
    return imie;
}

string Autor::getNazwisko() {
    return nazwisko;
}

