//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.cpp
//  @ Date : 17.03.2024
//  @ Author :
//
//


#include "Ksiazka.h"
#include <string>
#include <iostream>

using namespace std;


void Ksiazka::setTytul(string tytul) {

}

void Ksiazka::setRokWydania(int rok) {

}

Ksiazka::Ksiazka(string tytul, int rokWydania, Autor * autor) {
    this->tytul = tytul;
    this->rokWydania = rokWydania;
    this->autorKsiazki = autor;
}

string Ksiazka::getTytul() {
    return tytul;
}

int Ksiazka::getRokWydania() {
    return rokWydania;
}

void Ksiazka::getAutor() {
    cout << autorKsiazki->getImie() << " " << autorKsiazki->getNazwisko() << endl;
}

