//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Paczka.cpp
//  @ Date : 17.03.2024
//  @ Author :
//
//


#include "Paczka.h"
#include <iostream>
#include <string>

using namespace std;

Paczka::Paczka(string adres, bool czyOplacone) {
    this->adres = adres;
    this->czyOplacone;
    this->czyDostarczone = 0;
}

void Paczka::zmienStatus(bool status) {
    this->czyDostarczone = status;
}

bool Paczka::getStatus() {
    return czyDostarczone;
}

bool Paczka::getOplacone() {
    return czyOplacone;
}

