//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Paczka.h
//  @ Date : 17.03.2024
//  @ Author :
//
//


#if !defined(_PACZKA_H)
#define _PACZKA_H
#include <iostream>
#include <string>

using namespace std;

class Paczka {
public:
	Paczka(string adres, bool czyOplacone);
	void zmienStatus(bool status);
	bool getStatus();
	bool getOplacone();
private:
	string adres;
	bool czyOplacone;
	bool czyDostarczone;
};

#endif  //_PACZKA_H
