//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Dzial.h
//  @ Date : 08.04.2024
//  @ Author :
//
//


#if !defined(_DZIAL_H)
#define _DZIAL_H
#include "kierownikDzialu.h"
#include <iostream>
#include <string>

using namespace std;


class Dzial {
public:
	string nazwaDzialu;
	kierownikDzialu * kierownik;
	Dzial(string nazwa);
	~Dzial();
	void setNazwaDzialu();
	string getNazwaDzialu();
	void setKierownik(string imie, string nazwisko);
	kierownikDzialu * getKierownik();
};

#endif  //_DZIAL_H
