//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Dzial.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//

#include "kierownikDzialu.h"
#include "Dzial.h"
#include <iostream>
#include <string>

using namespace std;

Dzial::Dzial(string nazwa) {
    cout << "Konstruktor Dzialu" << endl;
    this->nazwaDzialu = nazwa;

    kierownik = new kierownikDzialu();
}

Dzial::~Dzial() {
    delete kierownik;
    cout << "Destruktor Dzialu" << endl;
}

void Dzial::setNazwaDzialu() {
    this->nazwaDzialu = nazwaDzialu;
}

string Dzial::getNazwaDzialu() {
    return nazwaDzialu;
}

void Dzial::setKierownik(string imie, string nazwisko){
    kierownik->setImie(imie);
    kierownik->setNazwisko(nazwisko);
}

kierownikDzialu * Dzial::getKierownik(){
    return kierownik;
}

