//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Firma.h
//  @ Date : 08.04.2024
//  @ Author :
//
//


#if !defined(_FIRMA_H)
#define _FIRMA_H
#include "Dzial.h"
#include <iostream>
#include <string>
#include <vector>

using namespace std;


class Firma {
public:
	Firma(string nazwa, int NIP, string wlasciciel);
	void dodajDzial(Dzial * dzial);
	void usunDzial(Dzial * dzial);
	void setNazwa(string nazwa);
	void setNIP(int nip);
	void setWlasciciel(string wlasciciel);
	string getNazwa();
	int getNIP();
	string getWlasciciel();
	void wyswietlDzialy();
	~Firma();
private:
	string nazwa;
	int NIP;
	string wlasciciel;
	vector<Dzial *> dzialy;
};

#endif  //_FIRMA_H
