//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : kierownikDzialu.cpp
//  @ Date : 08.04.2024
//  @ Author :
//
//


#include "kierownikDzialu.h"
#include <iostream>
#include <string>

using namespace std;

kierownikDzialu::kierownikDzialu() {
    cout << "Konstruktor Kierownika" << endl;
}

kierownikDzialu::~kierownikDzialu() {
    cout << "Destruktor Kierownika" << endl;
}

void kierownikDzialu::setImie(string imie){
    this->imie = imie;
}

void kierownikDzialu::setNazwisko(string nazwisko) {
    this->nazwisko = nazwisko;
}

string kierownikDzialu::getNazwisko() {
    return nazwisko;
}

string kierownikDzialu::getImie() {
    return imie;
}

