//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : kierownikDzialu.h
//  @ Date : 08.04.2024
//  @ Author :
//
//


#if !defined(_KIEROWNIKDZIALU_H)
#define _KIEROWNIKDZIALU_H
#include <iostream>
#include <string>

using namespace std;


class kierownikDzialu {
public:
	string imie;
	string nazwisko;
	kierownikDzialu();
	~kierownikDzialu();
	void setImie(string imie);
	void setNazwisko(string nazwisko);
	string getNazwisko();
	string getImie();
};

#endif  //_KIEROWNIKDZIALU_H
