//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 10.03.2024
//  @ Author :
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"
#include "string"

using namespace std;

class Jamnik : public Pies {
public:
	string wydajGlos();
	void jedz();
	Jamnik(string imie, string wlasciciel, int wiek);
private:
	string imie;
	string wlasciciel;
	int wiek;
};

#endif  //_JAMNIK_H
