//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 10.03.2024
//  @ Author :
//
//


#include "Jamnik.h"
#include "string"

using namespace std;

string Jamnik::wydajGlos() {
    return "hauhau";
}

void Jamnik::jedz() {

}

Jamnik::Jamnik(string imie, string wlasciciel, int wiek) {
    imie = imie;
    wlasciciel = wlasciciel;
    wiek = wiek;
}

