//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 10.03.2024
//  @ Author :
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"
#include <string>

using namespace std;

class Pies : public Ssak {
public:
	void wykonajSztuczke();
	void setRasa(string rasa);
	void setUmaszczenie(string umaszczenie);
	string getRasa();
	string getUmaszczenie();
private:
	string rasa;
	string umaszczenie;
};

#endif  //_PIES_H
