//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 10.03.2024
//  @ Author : 
//
//


#include "Ssak.h"

void Ssak::przemieszczanie() {

}

