//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 10.03.2024
//  @ Author :
//
//


#if !defined(_SSAK_H)
#define _SSAK_H
#include <string>

using namespace std;


class Ssak {
public:
	void przemieszczanie();
	void setWaga(float waga);
	void setSrodowisko(string srodowisko);
	float getWaga();
	string getSrodowisko();
private:
	string srodowiskoWystepowania;
	float waga;
};

#endif  //_SSAK_H
