//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 10.03.2024
//  @ Author :
//
//


#include "Ssak.h"
#include <string>
#include <iostream>

using namespace std;

void Ssak::przemieszczanie() {

}

void Ssak::setWaga(float waga) {
    this->waga = waga;
}

void Ssak::setSrodowisko(string srodowisko) {
    this->srodowiskoWystepowania = srodowisko;
}

float Ssak::getWaga() {
    return waga;
}

string Ssak::getSrodowisko() {
    return srodowiskoWystepowania;
}

