//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 10.03.2024
//  @ Author :
//
//

#include "string"
#if !defined(_SSAK_H)
#define _SSAK_H

using namespace std;

class Ssak {
public:
	void przemieszczanie();
private:
	string srodowiskoWystepowania;
	float waga;
};

#endif  //_SSAK_H
