//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 07.04.2024
//  @ Author :
//
//


#include "Pies.h"
#include <iostream>
#include <string>

using namespace std;

Pies::Pies(string imie, string rasa) {
    this->imie = imie;
    this->rasa = rasa;
}

void Pies::setImie(string imie) {
    this->imie = imie;
}

void Pies::setRasa(string rasa) {
    this->rasa = rasa;
}

string Pies::getImie() {
    return imie;
}

string Pies::getRasa() {
    return rasa;
}

