//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 07.04.2024
//  @ Author :
//
//


#if !defined(_SSAK_H)
#define _SSAK_H
#include <iostream>
#include <string>

using namespace std;

class Ssak {
public:
	void setSrodowisko(string srodowisko);
	void setWaga(float waga);
	string getSrodowisko();
	float getWaga();
private:
	string srodowiskoWystepowania;
	float waga;
};

#endif  //_SSAK_H
