//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PlatformaVOD.h
//  @ Date : 12.03.2024
//  @ Author :
//
//


#if !defined(_PLATFORMAVOD_H)
#define _PLATFORMAVOD_H

#include "Serial.h"
#include <string>
#include <iostream>
#include <vector>

using namespace std;

class PlatformaVOD {
public:
	void dodajSerial(Serial serial);
	void usunSerial(Serial serial);
	void getSeriale();
	string getNazwa();
	PlatformaVOD(string nazwa);
private:
	string nazwa;
	vector<Serial> seriale;
};

#endif  //_PLATFORMAVOD_H
