//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serial.cpp
//  @ Date : 12.03.2024
//  @ Author :
//
//


#include "Serial.h"
#include <string>
#include <iostream>

using namespace std;

Serial::Serial(string nazwa, string rezyser, int rokProdukcji) {
    this->nazwaSerialu = nazwa;
    this->rezyser = rezyser;
    this->rokProdukcji = rokProdukcji;
}

string Serial::getNazwaSerialu() {
    return nazwaSerialu;
}

string Serial::getRezyser() {
    return rezyser;
}

int Serial::getRokProdukcji() {
    return rokProdukcji;
}

