//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernouli.h
//  @ Date : 21.04.2024
//  @ Author :
//
//


#if !defined(_BERNOULI_H)
#define _BERNOULI_H
#include "Newton.h"
#include "Potegowanie.h"


class Bernouli {
public:
	Bernouli();
	~Bernouli();
	long double obliczPrawdopodobienstwo(long double p, int n, int k);
private:
	Potegowanie * potegowanie;
	Newton * newton;
};

#endif  //_BERNOULI_H
