//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernouli.cpp
//  @ Date : 21.04.2024
//  @ Author :
//
//


#include "Bernouli.h"
#include "Newton.h"
#include "Potegowanie.h"

Bernouli::Bernouli() {
    newton = new Newton();
    potegowanie = new Potegowanie();
}

Bernouli::~Bernouli() {
    delete newton;
    delete potegowanie;
}

long double Bernouli::obliczPrawdopodobienstwo(long double p, int n, int k) {
    return newton->obliczNewtona(n, k) * potegowanie->obliczPotege(p, k) * potegowanie->obliczPotege(1 - p, n-k);
}

