//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.cpp
//  @ Date : 21.04.2024
//  @ Author :
//
//


#include "Newton.h"

Newton::Newton() {
    silnia = new Silnia();
}

Newton::~Newton() {
    delete silnia;
}

long double Newton::obliczNewtona(int n, int k) {
    return (silnia->oblicz(n)/ (silnia->oblicz(k) * silnia->oblicz(n-k)));
}

