//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.h
//  @ Date : 21.04.2024
//  @ Author :
//
//


#if !defined(_NEWTON_H)
#define _NEWTON_H
#include "Silnia.h"


class Newton {
public:
	Newton();
	~Newton();
	long double obliczNewtona(int n, int k);
private:
	Silnia * silnia;
};

#endif  //_NEWTON_H
