//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potegowanie.cpp
//  @ Date : 21.04.2024
//  @ Author :
//
//


#include "Potegowanie.h"

Potegowanie::Potegowanie() {

}

Potegowanie::~Potegowanie() {

}

long double Potegowanie::obliczPotege(long double liczba, int potega) {
    double result = liczba;

    if (potega == 0) {
        return 1;
    }

    for(int i = 0; i < potega - 1; i++){
        result = result * liczba;
    }

    return result;
}

