//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potegowanie.h
//  @ Date : 21.04.2024
//  @ Author :
//
//


#if !defined(_POTEGOWANIE_H)
#define _POTEGOWANIE_H


class Potegowanie {
public:
	Potegowanie();
	~Potegowanie();
	long double obliczPotege(long double liczba, int potega);
};

#endif  //_POTEGOWANIE_H
