//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.h
//  @ Date : 21.04.2024
//  @ Author : 
//
//


#if !defined(_SILNIA_H)
#define _SILNIA_H


class Silnia {
public:
	Silnia();
	~Silnia();
	int oblicz(int n);
};

#endif  //_SILNIA_H
