//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.cpp
//  @ Date : 21.04.2024
//  @ Author :
//
//


#include "Silnia.h"

Silnia::Silnia() {

}

Silnia::~Silnia() {

}

int Silnia::oblicz(int n) {
    int result = 1;

    if (n == 0){
        return 1;
    }

    for(int i = 1; i <= n; i++){
        result = result * i;
    }

    return result;
}

