//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//

#include "System.h"
#include "User.h"
#include <iostream>
#include <string>
#include <vector>
using namespace std;

bool System::uwierzytelnianie(string login, string haslo) {

    bool isUser = 0;

    for(int i = 0; i < uzytkownicy.size(); i++){
        if(uzytkownicy[i]->getHaslo() == haslo && uzytkownicy[i]->getLogin() == login){
            isUser = 1;
        }
    }

    return isUser;
}

void System::dodajUser(User * user) {
    uzytkownicy.push_back(user);
}

