//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//


#include "User.h"
#include <iostream>
#include <string>
#include <vector>
using namespace std;

void User::logowanie() {

    cout << "Logowanie do systemu " << endl;
    string login, haslo;

    cout << "Podaj login: ";
    cin >> login;

    cout << "Podaj haslo: ";
    cin >> haslo;

    if(system->uwierzytelnianie(login, haslo)){
        cout << "Poprawnie zalogowano " << endl;
    }else{
        int choice;
        cout << "Wybierz opcje:\n1 - logowanie\n2 - rejestracja" << endl;
        cin >> choice;

        if(choice == 1){
            this->logowanie();
        }else if(choice == 2){
            this->rejestracja(this);
        }else{
            cout << "Bledna opcja" << endl;
        }
    }
}

void User::rejestracja(User * user) {
    cout << "Rejestracja " << endl;

    string login, haslo;
    cout << "Podaj login" << endl;
    cin >> login;
    cout << "Podaj haslo" << endl;
    cin >> haslo;

    this->login = login;
    this->haslo = haslo;
    system->dodajUser(user);

    cout << "Zarejestrowano uzytkownika" << endl;
    this->logowanie();
}

void User::wyloguj() {
    this->logowanie();
}

//User::User(string login, string haslo) {
//    this->login = login;
//    this->haslo = haslo;
//}

void User::dodajSystem(System * system) {
    this->system = system;
}

string User::getHaslo(){
    return haslo;
}

string User::getLogin(){
    return login;
}

