//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//


#include "User.h"
#include <iostream>
#include <string>
#include <vector>
using namespace std;

int User::logowanie() {

    int choice;
    cout << "Wybierz opcje:\n1 - logowanie\n2 - rejestracja\n3 - wyjscie z systemu" << endl;
    cin >> choice;

    if(choice == 1){

        cout << "Logowanie do systemu " << endl;
        string login, haslo;

        cout << "Podaj login: ";
        cin >> login;

        cout << "Podaj haslo: ";
        cin >> haslo;

        if(system->uwierzytelnianie(login, haslo)){
            cout << "Poprawnie zalogowano " << endl;
            int option;
            cout << "Wybierz 1 aby sie wylogowac: ";
            cin >> option;

            if(option == 1){
                this->wyloguj();
            }
        }else {
            cout << "Bledne dane do logowania" << endl;
            this->logowanie();
        }

    }else if(choice == 2){
        this->rejestracja(this);
    }else if(choice == 3){
        return 0;
    }
}

void User::rejestracja(User * user) {
    cout << "Rejestracja " << endl;

    string login, haslo;
    cout << "Podaj login: ";
    cin >> login;
    cout << "Podaj haslo: ";
    cin >> haslo;

    this->login = login;
    this->haslo = haslo;
    system->dodajUser(user);

    cout << "Zarejestrowano uzytkownika" << endl;
    this->logowanie();
}

void User::wyloguj() {
    cout << "Zostales wylogowany " << endl;
    this->logowanie();
}

void User::dodajSystem(System * system) {
    this->system = system;
}

string User::getHaslo(){
    return haslo;
}

string User::getLogin(){
    return login;
}

