//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 09.04.2024
//  @ Author :
//
//


#if !defined(_USER_H)
#define _USER_H
#include "System.h"
#include <iostream>
#include <string>
#include <vector>
using namespace std;


class System;

class User {
public:
	System * system;
	int logowanie();
	void rejestracja(User * user);
	void wyloguj();
//	User(string login, string haslo);
	void dodajSystem(System * system);
	string getLogin();
	string getHaslo();
private:
	string login;
	string haslo;
};

#endif  //_USER_H
